# Generated by Django 5.2 on 2025-05-29 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_worker_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='unread',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dailywork',
            name='sana',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
