# Generated by Django 5.2 on 2025-05-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_worker_unread_alter_dailywork_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='ishlangan',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='tolangan',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
