# Generated by Django 5.2 on 2025-05-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_message_manager'),
        ('worker', '0003_worker_unread_alter_dailywork_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='views',
            field=models.ManyToManyField(blank=True, to='worker.worker'),
        ),
    ]
