# Generated by Django 5.2 on 2025-05-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_monthlypayment_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.managerprofile'),
        ),
    ]
