# Generated by Django 5.2 on 2025-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_monthlypayment_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
